### ISSUE TITLE
Ability to have custom destination paths

### ISSUE THREAD

**Issue by kbrashears5** [varunsridharan/action-github-workflow-sync#1]
Would like to have the ability to have custom destination paths. For example:

```yaml
WORKFLOW_FILES: |
  ./sync/dependabot.yml=./.github/dependabot.yml
```
I don't want the destination to be .github/workflows/dependabot.yml because then github thinks it's an action rather than a dependabot file.

**Comment by varunsridharan** [comment]
@kbrashears5 will add this in upcoming release.

**Comment by varunsridharan** [comment]
V2.0 now has this feature
