### ISSUE TITLE
Node.js 16 support

### ISSUE THREAD

**Issue by mgerlach** [varunsridharan/action-github-workflow-sync#24]
**Is your feature request related to a problem? Please describe.**

When using the action, the following warning shows up on the workflow run summary page under "Annotations":

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: varunsridharan/action-github-workflow-sync
```

**Describe the solution you'd like**
Please migrate to using node.js 16

**Comment by smlgbl** [comment]
Hi Martin,
I just created PR #25 for this!

**Comment by mgerlach** [comment]
fixed by #25

**Comment by mgerlach** [comment]
@varunsridharan thanks for merging #25, can you also make a patch release, please?

**Comment by mgerlach** [comment]
@varunsridharan could you release a patch version?

**Comment by varunsridharan** [comment]
@mgerlach sorry about the delay. it's merged and released.

**Comment by mgerlach** [comment]
Thanks! 🙏
