### ISSUE TITLE
Action fails - git configuration is incomplete

### ISSUE THREAD

**Issue by flxw** [varunsridharan/action-github-workflow-sync#4]
**Describe the bug**
Hi, thanks for providing this useful action.
Unfortunately it fails for us, because somehow the git user is not correctly set inside the action itself.

We are running the action inside our organization, the repos are not public.
Would you have an idea how to fix this?

Here is the log from the action

```
" "update-prod.yml
" "***" "false" "workflows" "false" "false"

🗃 Git Config
    > Name          : Github Actions Workflow Sync Bot
    > Email         : githubactionbot+workflowsync@gmail.com

 
⚙️ Basic Config
-------------------------------------------------------
  * DRY_RUN               : false
  * Total Repositories    : 1
  * Total Workflow Files  : 1
--------------------------------------------------------
 
📓  celonis/workflow-sync-test
  ⚙️ Repository Config
    Slug          : celonis/workflow-sync-test
    Branch        : default
    Url           : ***github.com/celonis/workflow-sync-test.git
    Local Path    : /workflow-sync/celonis/workflow-sync-test/default
  
  ✔️ Repository Cloned
  
  update-test.yml
    update-test.yml => update-test.yml
  
  Git Commit & Push Log
  ---------------------------------------------------
  
  *** Please tell me who you are.
  
  Run
  
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
  
  to set your account's default identity.
  Omit --global to set the identity only in this repository.
  
  fatal: unable to auto-detect email address (got 'root@6a55273d2ba1.(none)')
```

**Additional context**
This seems to happen in the `ghconfig` function.
I couldn't find the source of `/gh-toolkit/shell.sh` where the function for setting up git is most likely defined.

**Comment by varunsridharan** [comment]
@flxw sorry about that. can you please tell me what the version or the branch your are using for this action ?

it should be something like `varunsridharan/action-github-workflow-sync@{branch/version}`

**Comment by varunsridharan** [comment]
@flxw I think i was able to figure out the issue. was able to add a quick fix. please do check and let me know.

**Comment by flxw** [comment]
Thanks, that did the trick! I was using the version straight from the `main` branch
