### ISSUE TITLE
Add a SKIP_CI parameter to modify the commit message and avoid triggering automation

### ISSUE THREAD

**Issue by smusick-teamwork** [varunsridharan/action-github-workflow-sync#6]
**Is your feature request related to a problem? Please describe.**
I'd like to update a repository without kicking off that repo's build automation. 

**Describe the solution you'd like**
Since Github Actions now supports adding `[skip ci]` to the commit message (https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/), I'd like to be able to add it to the commit message
by setting a parameter/input.
It could be something as simple as `SKIP_CI: true`
This would result in a commit message something like "Files Synced | [skp ci] | Runner ID : ! | ⚡ Triggered By Name/Repo" 
Without that option, updating a config file could result in 100s of deployments kicking off at once.

**Describe alternatives you've considered**
A more flexible solution might be to edit part or the whole commit message by inputing a string.

**Additional context**
Might be useful to know that several CI engines support [skip ci] 

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
https://circleci.com/docs/2.0/skip-build/
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

Also, really love your work here. 
Great solution to a problem I've been trying to solve for far too long  👍

**Comment by varunsridharan** [comment]
Hi There

Requested feature has been added in V 3.1
