### ISSUE TITLE
'License' and 'Code of Conduct' files missing, links are broken

### ISSUE THREAD

**Issue by groscoe** [varunsridharan/action-github-workflow-sync#7]
First of all, thanks for this action. 

I've noticed that though the README has a section about the code being GPL-licensed, there are no LICENSE files that I could find (at least in the main branch)  and the links in the README are broken. This makes me a bit wary of using it in my projects and might discourage others from contributing.

**Comment by varunsridharan** [comment]
hi there

thanks for informing. its fixed now
